#!/usr/bin/python

import os
import subprocess
import string

from giftory import Giftory


def gifify(giftory, delta):
	# Determine the type of edit
	delta = delta.strip() 
	delta = delta.replace("  ", " ") # Files can have two statuses, e.g. AM, or just A
	edit_kind, file = delta.split(" ")

	# Exclude those that are being deleted
	# In the future we may want to also auto-delete its gifs
	if "D" in edit_kind or "?" in edit_kind:
		return
	
	# Create gifs directory
	dir = os.path.dirname(file) 
	if not dir: # Top level directory
		dir = "."
	dir = dir + "/gifs"
	if not os.path.exists(dir):
		os.makedirs(dir)

	# Now make the gif
	giftory.make_historic_gif(file, dir)

	# Now add the gif to git index for committing
	p = subprocess.Popen(['git','add', dir+'/*', ], stdout=subprocess.PIPE, stderr=subprocess.PIPE)			
	p.communicate()

def main():
	giftory = Giftory()
	
	# A nicer way to define the filter types would be good
	p = subprocess.Popen(['git','status', '--porcelain'] + giftory.get_prop("filetypes"), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
	out, err = p.communicate()

	delta = out.splitlines(False)
	

	for d in delta:
		gifify(giftory, d)

if __name__ == '__main__':
	main()
